auth_magic: FtT3PsqwqxOivIiwui8RUB6JxpvHAPst
password_hash_algos: sha256
shop_name: ふまねっと
force_ssl: null
admin_allow_host: {  }
cookie_lifetime: 0
cookie_name: eccube
locale: ja
timezone: Asia/Tokyo
pageinrange: false
trusted_proxies_connection_only: false
trusted_proxies: {  }
eccube_install: 1
