database:
    driver: 'pdo_mysql'
    host: '127.0.0.1'
    dbname: 'ec_trial_temp'
    port: '3306'
    user: 'root'
    password : ''
    charset: utf8
    defaultTableOptions: { collate: utf8_general_ci }
