database:
    driver: 'pdo_mysql'
    host: '127.0.0.1'
    dbname: 'fumanet'
    port: '3306'
    user: 'fumanet'
    password : 'password1to3'
    charset: utf8
    defaultTableOptions: { collate: utf8_general_ci }
