root: /
admin_dir: ecTrial/
tpl: /user_data/packages/default/
admin_tpl: /user_data/packages/admin/
image_path: /upload/save_image/
root_dir: /var/www/ec_trial
root_urlpath: null
template_code: L3001
admin_route: ecTrial
user_data_route: user_data
public_path: /html
public_path_realdir: /var/www/ec_trial/html
image_save_realdir: /var/www/ec_trial/html/upload/save_image
image_temp_realdir: /var/www/ec_trial/html/upload/temp_image
user_data_realdir: /var/www/ec_trial/html/user_data
block_default_realdir: /var/www/ec_trial/src/Eccube/Resource/template/default/Block
block_realdir: /var/www/ec_trial/app/template/L3001/Block
template_default_realdir: /var/www/ec_trial/src/Eccube/Resource/template/default
template_default_html_realdir: /var/www/ec_trial/html/template/default
template_admin_realdir: /var/www/ec_trial/src/Eccube/Resource/template/admin
template_admin_html_realdir: /var/www/ec_trial/html/template/admin
template_realdir: /var/www/ec_trial/app/template/L3001
template_html_realdir: /var/www/ec_trial/html/template/L3001
template_temp_realdir: /var/www/ec_trial/app/cache/eccube/template
csv_temp_realdir: /var/www/ec_trial/app/cache/eccube/csv
plugin_realdir: /var/www/ec_trial/app/Plugin
plugin_temp_realdir: /var/www/ec_trial/app/cache/plugin
plugin_html_realdir: /var/www/ec_trial/html/plugin
admin_urlpath: /template/admin
front_urlpath: /template/L3001
image_save_urlpath: /upload/save_image
image_temp_urlpath: /upload/temp_image
user_data_urlpath: /user_data
plugin_urlpath: /plugin
