root: /
admin_dir: admin_fumanet/
tpl: /user_data/packages/default/
admin_tpl: /user_data/packages/admin/
image_path: /upload/save_image/
customer_image_path: /upload/customer_image/
questionnaire_attachment_path: /upload/questionnaire_attachment/
root_dir: /var/www/fumanet.com
root_urlpath: null
template_code: L3001
admin_route: ecTrial
user_data_route: user_data
public_path: /html
public_path_realdir: /var/www/fumanet.com/html
image_save_realdir: /var/www/fumanet.com/html/upload/save_image
image_temp_realdir: /var/www/fumanet.com/html/upload/temp_image
customer_image_save_realdir: /var/www/fumanet.com/html/upload/customer_image
questionnaire_attachment_save_realdir: /var/www/fumanet.com/html/upload/questionnaire_attachment
file_temp_realdir: /var/www/fumanet.com/html/upload/temp_file
product_image_save_realdir: /var/www/fumanet.com/html/upload/product_image
product_file_save_realdir: /var/www/fumanet.com/html/upload/product_file
user_data_realdir: /var/www/fumanet.com/html/user_data
block_default_realdir: /var/www/fumanet.com/src/Eccube/Resource/template/default/Block
block_realdir: /var/www/fumanet.com/app/template/L3001/Block
template_default_realdir: /var/www/fumanet.com/src/Eccube/Resource/template/default
template_default_html_realdir: /var/www/fumanet.com/html/template/default
template_admin_realdir: /var/www/fumanet.com/src/Eccube/Resource/template/admin
template_admin_html_realdir: /var/www/fumanet.com/html/template/admin
template_realdir: /var/www/fumanet.com/app/template/L3001
template_html_realdir: /var/www/fumanet.com/html/template/L3001
template_temp_realdir: /var/www/fumanet.com/app/cache/eccube/template
csv_temp_realdir: /var/www/fumanet.com/app/cache/eccube/csv
plugin_realdir: /var/www/fumanet.com/app/Plugin
plugin_temp_realdir: /var/www/fumanet.com/app/cache/plugin
plugin_html_realdir: /var/www/fumanet.com/html/plugin
admin_urlpath: /template/admin
front_urlpath: /template/L3001
image_save_urlpath: /upload/save_image
image_temp_urlpath: /upload/temp_image
customer_image_save_urlpath: /upload/customer_image
product_image_save_urlpath: /upload/product_image
product_file_save_urlpath: /upload/product_file
questionnaire_attachment_save_urlpath: /upload/questionnaire_attachment
file_temp_urlpath: /upload/temp_file
user_data_urlpath: /user_data
plugin_urlpath: /plugin
qr_code_get_url: http://fumanet.com/qr-code/qr_img.php?d=
