<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerBasicInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerBasicInfoRepository extends EntityRepository
{
    public function getCustomerBasicInfoByCustomer(\Eccube\Entity\Customer $Customer)
    {
        return $this->createQueryBuilder('c')
                ->where('c.Customer = :Customer')
                ->setParameter('Customer', $Customer)
                ->getQuery()
                ->getOneOrNullResult();
    }

    public function getCustomerBasicInfoByMembershipExemption(\Eccube\Entity\Master\ExemptionType $ExemptionType)
    {

        return $this->createQueryBuilder("c")
                ->where("c.MembershipExemption = :ExemptionType")
                ->setParameter('ExemptionType', $ExemptionType)
                ->getQuery()
                ->getResult();
    }

    public function clearMembershipExemption()
    {
        $em = $this->getEntityManager();
        $sql = "UPDATE dtb_customer_basic_info SET dtb_customer_basic_info.membership_exemption = 1;";
        $result = $em->getConnection()->executeQuery($sql, array());
        return $result;
    }
}
