<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembershipBillingDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipBillingDetailRepository extends EntityRepository
{
    public function insertAllTarget($targeBillingId, $targetProducts = array(), $targetStatus = array())
    {
        $em = $this->getEntityManager();
        $sql = "INSERT INTO dtb_membership_billing_detail (membership_billing, customer, status, create_date, update_date)";
        $sql .= " SELECT " . $targeBillingId . ", dtb_customer.customer_id, 1, NOW(), NOW() FROM dtb_customer ";
        if (0 < count($targetStatus)) {
            $sql .= "INNER JOIN dtb_customer_basic_info ON dtb_customer.customer_id = dtb_customer_basic_info.customer_id ";
        }
        $sql .= "WHERE (";
        $loop = 0;
        foreach ($targetProducts as $targetProduct) {
            $sql .= ((0 < $loop)?" OR ":" ") . "dtb_customer.customer_id NOT IN ";
            $sql .= "(SELECT dtb_customer.customer_id FROM dtb_customer INNER JOIN dtb_order ON dtb_customer.customer_id = dtb_order.customer_id ";
            $sql .= "INNER JOIN dtb_order_detail ON dtb_order.order_id = dtb_order_detail.order_id ";
            $sql .= "WHERE dtb_order_detail.product_id = " . $targetProduct;
            $sql .= " GROUP BY dtb_customer.customer_id) ";
            if (0 < count($targetStatus)) {
                $sql .= "AND dtb_customer_basic_info.status in (";
                $cnt = 0;
                foreach($targetStatus as $status) {
                    $sql .= ((0 < $cnt)?",":"") . $status;
                    ++$cnt;
                }
                $sql .= ") ";
            }
            ++$loop;
        }
        $sql .= ") ";
        $sql .= "ORDER BY dtb_customer.customer_id DESC;";
        $result = $em->getConnection()->executeQuery($sql);

        return $result;
    }
}
