<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductMembershipRepository extends EntityRepository
{
    /**
     * @var \Eccube\Application
     */
    protected $app;

    public function setApplication(Application $app)
    {
        $this->app = $app;
    }

    /**
     * 年会費一覧を取得する.
     *
     * @return \Eccube\Entity\ProductMembership[] 年会費の配列
     */
    public function getList(Category $Parent = null, $flat = false)
    {
        $options = $this->app['config']['doctrine_cache'];
        $lifetime = $options['result_cache']['lifetime'];

        $qb = $this->createQueryBuilder('pm')
            ->select('pm')
            ->orderBy('pm.membership_year', 'DESC');
        $ProductMembership = $qb->getQuery()
            ->useResultCache(true, $lifetime)
            ->getResult();

        return $ProductMembership;
    }


    /**
     * 年会費登録有無を取得する.
     *
     * @return 年会費登録有無
     */
    public function isExistsMembership($membershipYear, $exclusionProductId = false)
    {
        $qb = $this->createQueryBuilder('pm')
            ->leftJoin('pm.Product', 'p')
            ->select('pm')
            ->where('pm.membership_year = :membership_year')
            ->setParameters(array(
                'membership_year' => $membershipYear
            ))
            ->orderBy('pm.membership_year', 'DESC');
        if (!is_null($exclusionProductId)) {
            $qb
                ->andWhere('p.id <> :product_id')
                ->setParameter('product_id', $exclusionProductId);
        }
        $ProductMembership = $qb->getQuery()
            ->getResult();
        return (0 < count($ProductMembership));
    }

    public function getMembershipProductName($membershipYear)
    {
        $productMembership = $this->createQueryBuilder('pm')
            ->where('pm.membership_year = :membership_year')
            ->setParameter('membership_year', $membershipYear)
            ->getQuery()
            ->getOneOrNullResult();
        
        if (isset($productMembership)) {
            return $productMembership->getProduct()->getName();
        }
            
        return '';
    }

    public function getProductMembershipByMembershipYear($membershipYear)
    {
        $productMembership = $this->createQueryBuilder('pm')
            ->where('pm.membership_year = :membership_year')
            ->setParameter('membership_year', $membershipYear)
            ->getQuery()
            ->getOneOrNullResult();
        
        return $productMembership;
    }

    public function existsMembershipProductOrderByMembershipYear($customerId, $membershipYear)
    {
        $productMembership = $this->createQueryBuilder('pm')
            ->where('pm.membership_year = :membership_year')
            ->setParameter('membership_year', $membershipYear)
            ->getQuery()
            ->getOneOrNullResult();
        if (is_null($productMembership)) {
            return false;
        }
        $key = sprintf("%011d%011d", $customerId, $productMembership->getProduct()->getId());
        $em = $this->getEntityManager();
        $sql = "SELECT";
        $sql .= " COUNT(dtb_order.order_id)";
        $sql .= " FROM";
        $sql .= " dtb_order";
        $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id";
        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id";
        $sql .= " WHERE";
        $sql .= " CONCAT(LPAD(dtb_order.customer_id, 11, '0'), LPAD(dtb_order_detail.product_id, 11, '0')) = " . $key;
        $sql .= " AND dtb_order.del_flg <> 1;";
        $result = $em->getConnection()->fetchColumn($sql);
        return (0 < $result);
    }

    /**
     * get query builder.
     *
     * @param  array $searchData
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getProductMembershipQueryBuilderByMembershipId($MembershipId)
    {
        $qb = $this->createQueryBuilder('pm');
        if (is_array($MembershipId)) {
            $qb->andWhere($qb->expr()->in('pm.id', ':MembershipId'))
                ->setParameter('MembershipId', $MembershipId);
        } else {
            $qb->andWhere('pm.id = :MembershipId')
                ->setParameter('MembershipId', $MembershipId);
        }

        // Order By
        // XXX Paginater を使用した場合に PostgreSQL で正しくソートできない
        $qb->addOrderBy('pm.id', 'DESC');

        return $qb;
    }
}
