<?php

namespace Eccube\Command;

use Doctrine\Common\Collections\ArrayCollection;
use Eccube\Common\Constant;
use Eccube\Entity\Master\DeviceType;
use Eccube\Entity\ShipmentItem;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Helper\TableHelper;

class MembershipBillingCommand extends \Knp\Command\Command
{

    protected $app;

    protected function configure() {
        $this
            ->setName('membershipbilling:billing')
            ->setDescription('Membership Billing For All Target Customer')
            ->addArgument('BillingId', InputArgument::REQUIRED, 'What invoice do you give?');
    }

    protected function execute(InputInterface $input, OutputInterface $output) {
        $this->app = $this->getSilexApplication();
        $this->app->initialize();
        $this->app->boot();
        $console = new Application();
        $this->app['orm.em']->getConnection()->getConfiguration()->setSQLLogger(null);
        $BillingId = $input->getArgument('BillingId');
        $logfile_path = $this->app['config']['root_dir'].'/app/log/MembershipBilling.log';
        file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '年会費受注登録バッチ起動 BillingId:' . $BillingId . "\n", FILE_APPEND);
        $membershipBilling = $this->app['eccube.repository.membership_billing']
                    ->find($BillingId);
        if ($membershipBilling) {
            if ($membershipBilling->getStatus()->getId() == 1) {
                $total = count($membershipBilling->getMembershipBillingDetail());
                file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '受注登録開始:' . $total . "\n", FILE_APPEND);
                // 処理状態更新
                $membershipBilling->setStatus($this->app['eccube.repository.master.membership_billing_status']->find(2));
                $this->app['orm.em']->persist($membershipBilling);
                $this->app['orm.em']->flush();
                try {
                    $this->app['orm.em']->getConnection()->beginTransaction();

                    $sql = " SELECT\n";
                    $sql .= " count(*)\n";
                    $sql .= " FROM(\n";
                    $sql .= " SELECT\n";
                    $sql .= " dtb_customer.customer_id\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_membership_billing\n";
                    $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                    $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                    $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                    $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (' . "\n";
                    $sql .= " SELECT\n";
                    $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))' . "\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_order\n";
                    $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= " dtb_order.del_flg = 0\n";
                    $sql .= " )\n";
                    $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId;
                    $sql .= " AND (dtb_customer.customer_group IS NULL OR dtb_customer.customer_group = 0)\n";
                    $sql .= " GROUP BY\n";
                    $sql .= " dtb_customer.customer_id\n";
                    $sql .= ") AS TEMP;";
                    $total = $this->app['orm.em']->getConnection()->fetchColumn($sql);

                    file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '非グループ会員受注処理開始:' . $total . "\n", FILE_APPEND);
                    $sql = "UPDATE dtb_membership_billing_detail SET dtb_membership_billing_detail.status = 2, dtb_membership_billing_detail.update_date = NOW() WHERE dtb_membership_billing_detail.membership_billing = " . $BillingId . " AND dtb_membership_billing_detail.customer IN (\n";
                    $sql .= " SELECT\n";
                    $sql .= " customer_id\n";
                    $sql .= " FROM(\n";
                    $sql .= " SELECT\n";
                    $sql .= " dtb_customer.customer_id\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_membership_billing\n";
                    $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                    $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                    $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                    $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (' . "\n";
                    $sql .= " SELECT\n";
                    $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))' . "\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_order\n";
                    $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= " dtb_order.del_flg = 0\n";
                    $sql .= " )\n";
                    $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId;
                    $sql .= " AND (dtb_customer.customer_group IS NULL OR dtb_customer.customer_group = 0)\n";
                    $sql .= " GROUP BY\n";
                    $sql .= " dtb_customer.customer_id\n";
                    $sql .= ") AS TEMP\n";
                    $sql .= ");";
                    $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                    file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '非グループ会員受注登録:' . $total . "\n", FILE_APPEND);
                    $sql = "INSERT INTO dtb_order (`group_order_id`, `customer_id`, `customer_group_id`, `order_country_id`, `order_pref`, `order_sex`, `order_job`, `payment_id`, `device_type_id`, `pre_order_id`, `message`, `order_name01`, `order_name02`, `order_kana01`, `order_kana02`, `order_company_name`, `order_email`, `order_tel01`, `order_tel02`, `order_tel03`, `order_fax01`, `order_fax02`, `order_fax03`, `order_zip01`, `order_zip02`, `order_zipcode`, `order_addr01`, `order_addr02`, `order_birth`, `subtotal`, `discount`, `delivery_fee_total`, `charge`, `tax`, `total`, `payment_total`, `payment_method`, `note`, `create_date`, `update_date`, `order_date`, `commit_date`, `payment_date`, `del_flg`, `status`)\n";
                    $sql .= " SELECT\n";
                    $sql .= " NULL,\n";
                    $sql .= " TEMP.customer_id,\n";
                    $sql .= " NULL,\n";
                    $sql .= " TEMP.country_id,\n";
                    $sql .= " TEMP.pref,\n";
                    $sql .= " TEMP.sex,\n";
                    $sql .= " TEMP.job,\n";
                    $sql .= " 3,\n";
                    $sql .= " 99,\n";
                    $sql .= " NULL,\n";
                    $sql .= " NULL,\n";
                    $sql .= " TEMP.name01,\n";
                    $sql .= " TEMP.name02,\n";
                    $sql .= " TEMP.kana01,\n";
                    $sql .= " TEMP.kana02,\n";
                    $sql .= " TEMP.company_name,\n";
                    $sql .= " TEMP.email,\n";
                    $sql .= " TEMP.tel01,\n";
                    $sql .= " TEMP.tel02,\n";
                    $sql .= " TEMP.tel03,\n";
                    $sql .= " TEMP.fax01,\n";
                    $sql .= " TEMP.fax02,\n";
                    $sql .= " TEMP.fax03,\n";
                    $sql .= " TEMP.zip01,\n";
                    $sql .= " TEMP.zip02,\n";
                    $sql .= " TEMP.zipcode,\n";
                    $sql .= " TEMP.addr01,\n";
                    $sql .= " TEMP.addr02,\n";
                    $sql .= " TEMP.birth,\n";
                    $sql .= " TEMP.total,\n";
                    $sql .= " 0,\n";
                    $sql .= " 0,\n";
                    $sql .= " 0,\n";
                    $sql .= " 0,\n";
                    $sql .= " TEMP.total,\n";
                    $sql .= " TEMP.total,\n";
                    $sql .= ' "郵便振込",' . "\n";
                    $sql .= ' CONCAT("membership_bulk_", ' . $BillingId . ', "_", TEMP.customer_id), ' . "\n";
                    $sql .= " NOW(),\n";
                    $sql .= " NOW(),\n";
                    $sql .= " NOW(),\n";
                    $sql .= " NOW(),\n";
                    $sql .= " NOW(),\n";
                    $sql .= " 0,\n";
                    $sql .= " 5\n";
                    $sql .= " FROM (\n";
                    $sql .= " SELECT \n";
                    $sql .= " INNER_TEMP.customer_id,\n";
                    $sql .= " INNER_TEMP.customer_group,\n";
                    $sql .= " INNER_TEMP.country_id,\n";
                    $sql .= " INNER_TEMP.pref,\n";
                    $sql .= " INNER_TEMP.sex,\n";
                    $sql .= " INNER_TEMP.job,\n";
                    $sql .= " INNER_TEMP.name01, \n";
                    $sql .= " INNER_TEMP.name02, \n";
                    $sql .= " INNER_TEMP.kana01, \n";
                    $sql .= " INNER_TEMP.kana02, \n";
                    $sql .= " INNER_TEMP.company_name, \n";
                    $sql .= " INNER_TEMP.email, \n";
                    $sql .= " INNER_TEMP.tel01, \n";
                    $sql .= " INNER_TEMP.tel02, \n";
                    $sql .= " INNER_TEMP.tel03, \n";
                    $sql .= " INNER_TEMP.fax01, \n";
                    $sql .= " INNER_TEMP.fax02, \n";
                    $sql .= " INNER_TEMP.fax03, \n";
                    $sql .= " INNER_TEMP.zip01, \n";
                    $sql .= " INNER_TEMP.zip02, \n";
                    $sql .= " INNER_TEMP.zipcode, \n";
                    $sql .= " INNER_TEMP.addr01, \n";
                    $sql .= " INNER_TEMP.addr02, \n";
                    $sql .= " INNER_TEMP.birth,\n";
                    $sql .= " count(INNER_TEMP.product_id) AS quantity,\n";
                    $sql .= " SUM(INNER_TEMP.price) AS total\n";
                    $sql .= " FROM (\n";
                    $sql .= " SELECT\n";
                    $sql .= " dtb_membership_billing.membership_billing_id AS membership_billing_id,\n";
                    $sql .= " dtb_membership_billing_detail.membership_billing_detail_id AS membership_billing_detail_id,\n";
                    $sql .= " dtb_customer.customer_id AS customer_id,\n";
                    $sql .= " dtb_customer.customer_group AS customer_group,\n";
                    $sql .= " dtb_customer.country_id AS country_id,\n";
                    $sql .= " dtb_customer.pref AS pref,\n";
                    $sql .= " dtb_customer.sex AS sex,\n";
                    $sql .= " dtb_customer.job AS job,\n";
                    $sql .= " dtb_customer.name01 AS name01,\n";
                    $sql .= " dtb_customer.name02 AS name02,\n";
                    $sql .= " dtb_customer.kana01 AS kana01,\n";
                    $sql .= " dtb_customer.kana02 AS kana02,\n";
                    $sql .= " dtb_customer.company_name AS company_name,\n";
                    $sql .= " dtb_customer.email AS email,\n";
                    $sql .= " dtb_customer.tel01 AS tel01,\n";
                    $sql .= " dtb_customer.tel02 AS tel02,\n";
                    $sql .= " dtb_customer.tel03 AS tel03,\n";
                    $sql .= " dtb_customer.fax01 AS fax01,\n";
                    $sql .= " dtb_customer.fax02 AS fax02,\n";
                    $sql .= " dtb_customer.fax03 AS fax03,\n";
                    $sql .= " dtb_customer.zip01 AS zip01,\n";
                    $sql .= " dtb_customer.zip02 AS zip02,\n";
                    $sql .= " dtb_customer.zipcode AS zipcode,\n";
                    $sql .= " dtb_customer.addr01 AS addr01,\n";
                    $sql .= " dtb_customer.addr02 AS addr02,\n";
                    $sql .= " dtb_customer.birth AS birth,\n";
                    $sql .= " dtb_product_class.product_id AS product_id,\n";
                    $sql .= " dtb_product_class.price02 AS price\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_membership_billing\n";
                    $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                    $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                    $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                    $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (' . "\n";
                    $sql .= " SELECT\n";
                    $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))' . "\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_order\n";
                    $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= " dtb_order.del_flg = 0\n";
                    $sql .= " )\n";
                    $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId ."\n";
                    $sql .= " AND (dtb_customer.customer_group IS NULL OR dtb_customer.customer_group = 0)\n";
                    $sql .= " GROUP BY\n";
                    $sql .= " dtb_membership_billing.membership_billing_id,\n";
                    $sql .= " dtb_membership_billing_detail.membership_billing_detail_id,\n";
                    $sql .= " dtb_customer.customer_id,\n";
                    $sql .= " dtb_product_class.product_id\n";
                    $sql .= " ) AS INNER_TEMP\n";
                    $sql .= " GROUP BY INNER_TEMP.customer_id\n";
                    $sql .= " ORDER BY INNER_TEMP.customer_id\n";
                    $sql .= " ) AS TEMP;";
                    $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                    $sql = " SELECT\n";
                    $sql .= " count(*)\n";
                    $sql .= " FROM (\n";
                    $sql .= " SELECT\n";
                    $sql .= " dtb_membership_billing.membership_billing_id,\n";
                    $sql .= " dtb_membership_billing_detail.membership_billing_detail_id,\n";
                    $sql .= " dtb_customer.customer_id,\n";
                    $sql .= " dtb_product_class.product_id\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_membership_billing\n";
                    $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                    $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                    $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                    $sql .= " INNER JOIN dtb_product ON dtb_product.product_id = dtb_product_membership.product_id\n";
                    $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (' . "\n";
                    $sql .= " SELECT\n";
                    $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))' . "\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_order\n";
                    $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= " dtb_order.del_flg = 0\n";
                    $sql .= " )\n";
                    $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId . "\n";
                    $sql .= " AND (dtb_customer.customer_group IS NULL OR dtb_customer.customer_group = 0)\n";
                    $sql .= " GROUP BY\n";
                    $sql .= " dtb_membership_billing.membership_billing_id,\n";
                    $sql .= " dtb_membership_billing_detail.membership_billing_detail_id,\n";
                    $sql .= " dtb_customer.customer_id,\n";
                    $sql .= " dtb_product_class.product_id ) AS TEMP;";
                    $totalDetail = $this->app['orm.em']->getConnection()->fetchColumn($sql);

                    file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '非グループ会員受注詳細登録:' . $totalDetail . "\n", FILE_APPEND);
                    $sql = "INSERT INTO `dtb_order_detail` (`order_id`, `product_id`, `product_class_id`, `product_name`, `product_code`, `class_name1`, `class_name2`, `class_category_name1`, `class_category_name2`, `price`, `quantity`, `tax_rate`, `tax_rule`, `kifu_no_pub`)\n";
                    $sql .= " SELECT\n";
                    $sql .= " dtb_order.order_id AS order_id,\n";
                    $sql .= " dtb_product.product_id AS product_id,\n";
                    $sql .= " dtb_product_class.product_class_id AS product_class_id,\n";
                    $sql .= " dtb_product.name AS product_name,\n";
                    $sql .= " dtb_product_class.product_code AS product_code,\n";
                    $sql .= " NULL,\n";
                    $sql .= " NULL,\n";
                    $sql .= " NULL,\n";
                    $sql .= " NULL,\n";
                    $sql .= " dtb_product_class.price02 AS price,\n";
                    $sql .= " 1,\n";
                    $sql .= " 0,\n";
                    $sql .= " 0,\n";
                    $sql .= " 0\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_membership_billing\n";
                    $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                    $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                    $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                    $sql .= " INNER JOIN dtb_product ON dtb_product.product_id = dtb_product_membership.product_id\n";
                    $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                    $sql .= ' INNER JOIN dtb_order ON dtb_order.note = CONCAT("membership_bulk_", ' . $BillingId . ', "_", dtb_customer.customer_id)' . "\n";
                    $sql .= " WHERE\n";
                    $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (' . "\n";
                    $sql .= " SELECT\n";
                    $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))' . "\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_order\n";
                    $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= " dtb_order.del_flg = 0\n";
                    $sql .= " )\n";
                    $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId . "\n";
                    $sql .= " AND (dtb_customer.customer_group IS NULL OR dtb_customer.customer_group = 0)\n";
                    $sql .= " GROUP BY\n";
                    $sql .= " dtb_membership_billing.membership_billing_id,\n";
                    $sql .= " dtb_membership_billing_detail.membership_billing_detail_id,\n";
                    $sql .= " dtb_customer.customer_id,\n";
                    $sql .= " dtb_product_class.product_id;";
                    $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                    file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '一括登録情報へ非グループ会員受注情報登録:' . $total . "\n", FILE_APPEND);
                    $sql = 'UPDATE dtb_membership_billing_detail INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer AND (dtb_customer.customer_group IS NULL OR dtb_customer.customer_group = 0) INNER JOIN dtb_order ON dtb_order.note = CONCAT("membership_bulk_", dtb_membership_billing_detail.membership_billing, "_", dtb_membership_billing_detail.customer) SET dtb_membership_billing_detail.order_id = dtb_order.order_id WHERE dtb_membership_billing_detail.membership_billing = ' . $BillingId . ';';
                    $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                    file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '非グループ会員受注処理完了:' . $total . "\n", FILE_APPEND);
                    $sql = "UPDATE dtb_membership_billing_detail SET dtb_membership_billing_detail.status = 3, dtb_membership_billing_detail.update_date = NOW() WHERE dtb_membership_billing_detail.membership_billing = " . $BillingId . " AND dtb_membership_billing_detail.customer IN (\n";
                    $sql .= " SELECT\n";
                    $sql .= " dtb_order.customer_id\n";
                    $sql .= " FROM\n";
                    $sql .= " dtb_order\n";
                    $sql .= " WHERE\n";
                    $sql .= ' dtb_order.note LIKE CONCAT("membership_bulk_", ' . $BillingId . ', "%")' . "\n";
                    $sql .= " );";
                    $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                    $sql = " SELECT\n";
                    $sql .= " count(*)\n";
                    $sql .= " FROM(\n";
                    $sql .= " SELECT\n";
                    $sql .= " dtb_customer.customer_group\n";
                    $sql .= " FROM \n";
                    $sql .= " dtb_membership_billing\n";
                    $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                    $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                    $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                    $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (';
                    $sql .= " SELECT\n";
                    $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))';
                    $sql .= " FROM\n";
                    $sql .= " dtb_order\n";
                    $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                    $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                    $sql .= " WHERE\n";
                    $sql .= " dtb_order.del_flg = 0\n";
                    $sql .= " )\n";
                    $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId;
                    $sql .= " AND dtb_customer.customer_group IS NOT NULL \n";
                    $sql .= " AND dtb_customer.customer_group <> 0\n";
                    $sql .= " GROUP BY\n";
                    $sql .= " dtb_customer.customer_group\n";
                    $sql .= ") AS TEMP\n";
                    $totalGroup = $this->app['orm.em']->getConnection()->fetchColumn($sql);

                    if (0 < $totalGroup) {
                        file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . 'グループ会員受注処理開始:' . $totalGroup . "\n", FILE_APPEND);
                        $sql = "UPDATE dtb_membership_billing_detail SET dtb_membership_billing_detail.status = 2, dtb_membership_billing_detail.update_date = NOW() WHERE dtb_membership_billing_detail.membership_billing = " . $BillingId . " AND dtb_membership_billing_detail.customer IN (\n";
                        $sql .= " SELECT\n";
                        $sql .= " customer_id\n";
                        $sql .= " FROM(\n";
                        $sql .= " SELECT\n";
                        $sql .= " dtb_customer.customer_id\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_membership_billing\n";
                        $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                        $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                        $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                        $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                        $sql .= " WHERE\n";
                        $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (';
                        $sql .= " SELECT\n";
                        $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))';
                        $sql .= " FROM\n";
                        $sql .= " dtb_order\n";
                        $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                        $sql .= " WHERE\n";
                        $sql .= " dtb_order.del_flg = 0\n";
                        $sql .= " )\n";
                        $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId;
                        $sql .= " AND dtb_customer.customer_group IS NOT NULL \n";
                        $sql .= " AND dtb_customer.customer_group <> 0\n";
                        $sql .= " GROUP BY\n";
                        $sql .= " dtb_customer.customer_id\n";
                        $sql .= ") AS TEMP\n";
                        $sql .= ");\n";
                        $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                        $sql = " SELECT\n";
                        $sql .= " count(*)\n";
                        $sql .= " FROM (\n";
                        $sql .= " SELECT\n";
                        $sql .= " dtb_customer.customer_id\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_membership_billing\n";
                        $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                        $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                        $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                        $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                        $sql .= " WHERE\n";
                        $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (';
                        $sql .= " SELECT\n";
                        $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))';
                        $sql .= " FROM\n";
                        $sql .= " dtb_order\n";
                        $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                        $sql .= " WHERE\n";
                        $sql .= " dtb_order.del_flg = 0\n";
                        $sql .= " )\n";
                        $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId;
                        $sql .= " AND dtb_customer.customer_group IS NOT NULL \n";
                        $sql .= " AND dtb_customer.customer_group <> 0\n";
                        $sql .= " GROUP BY\n";
                        $sql .= " dtb_customer.customer_id) AS TEMP;";
                        $total = $this->app['orm.em']->getConnection()->fetchColumn($sql);

                        file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . 'グループ会員グループ受注登録:' . $total . "\n", FILE_APPEND);
                        $sql = "INSERT INTO `dtb_group_order` (`customer_group_id`, `name`, `kana`, `send_to_pref`, `send_to_zip01`, `send_to_zip02`, `send_to_zipcode`, `send_to_addr01`, `send_to_addr02`, `send_to_email`, `send_to_tel01`, `send_to_tel02`, `send_to_tel03`, `send_to_fax01`, `send_to_fax02`, `send_to_fax03`, `bill_to`, `bill_to_pref`, `bill_to_zip01`, `bill_to_zip02`, `bill_to_zipcode`, `bill_to_addr01`, `bill_to_addr02`, `bill_to_email`, `bill_to_tel01`, `bill_to_tel02`, `bill_to_tel03`, `bill_to_fax01`, `bill_to_fax02`, `bill_to_fax03`, `note`, `del_flg`, `create_date`, `update_date`, `order_date`)\n";
                        $sql .= " SELECT\n";
                        $sql .= " dtb_customer_group.customer_group_id AS customer_group_id,\n";
                        $sql .= " dtb_customer_group.name AS name, \n";
                        $sql .= " dtb_customer_group.kana AS kana, \n";
                        $sql .= " dtb_customer_group.send_to_pref AS send_to_pref, \n";
                        $sql .= " dtb_customer_group.send_to_zip01 AS send_to_zip01, \n";
                        $sql .= " dtb_customer_group.send_to_zip02 AS send_to_zip02, \n";
                        $sql .= " dtb_customer_group.send_to_zipcode AS send_to_zipcode, \n";
                        $sql .= " dtb_customer_group.send_to_addr01 AS send_to_addr01, \n";
                        $sql .= " dtb_customer_group.send_to_addr02 AS send_to_addr02, \n";
                        $sql .= " dtb_customer_group.send_to_email AS send_to_email, \n";
                        $sql .= " dtb_customer_group.send_to_tel01 AS send_to_tel01, \n";
                        $sql .= " dtb_customer_group.send_to_tel02 AS send_to_tel02, \n";
                        $sql .= " dtb_customer_group.send_to_tel03 AS send_to_tel03, \n";
                        $sql .= " dtb_customer_group.send_to_fax01 AS send_to_fax01, \n";
                        $sql .= " dtb_customer_group.send_to_fax02 AS send_to_fax02, \n";
                        $sql .= " dtb_customer_group.send_to_fax03 AS send_to_fax03, \n";
                        $sql .= " dtb_customer_group.bill_to AS bill_to, \n";
                        $sql .= " dtb_customer_group.bill_to_pref AS bill_to_pref, \n";
                        $sql .= " dtb_customer_group.bill_to_zip01 AS bill_to_zip01, \n";
                        $sql .= " dtb_customer_group.bill_to_zip02 AS bill_to_zip02, \n";
                        $sql .= " dtb_customer_group.bill_to_zipcode AS bill_to_zipcode, \n";
                        $sql .= " dtb_customer_group.bill_to_addr01 AS bill_to_addr01, \n";
                        $sql .= " dtb_customer_group.bill_to_addr02 AS bill_to_addr02, \n";
                        $sql .= " dtb_customer_group.bill_to_email AS bill_to_email, \n";
                        $sql .= " dtb_customer_group.bill_to_tel01 AS bill_to_tel01, \n";
                        $sql .= " dtb_customer_group.bill_to_tel02 AS bill_to_tel02, \n";
                        $sql .= " dtb_customer_group.bill_to_tel03 AS bill_to_tel03, \n";
                        $sql .= " dtb_customer_group.bill_to_fax01 AS bill_to_fax01, \n";
                        $sql .= " dtb_customer_group.bill_to_fax02 AS bill_to_fax02, \n";
                        $sql .= " dtb_customer_group.bill_to_fax03 AS bill_to_fax03, \n";
                        $sql .= ' CONCAT("membership_bulk_group_", ' . $BillingId . ', "_", dtb_customer_group.customer_group_id),' . "\n";
                        $sql .= " 0,\n";
                        $sql .= " NOW(),\n";
                        $sql .= " NOW(),\n";
                        $sql .= " NOW()\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_membership_billing\n";
                        $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                        $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                        $sql .= " INNER JOIN dtb_customer_group ON dtb_customer_group.customer_group_id = dtb_customer.customer_group\n";
                        $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                        $sql .= " WHERE\n";
                        $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (' . "\n";
                        $sql .= " SELECT\n";
                        $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))' . "\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_order\n";
                        $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                        $sql .= " WHERE\n";
                        $sql .= " dtb_order.del_flg = 0\n";
                        $sql .= " )\n";
                        $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId . "\n";
                        $sql .= " AND dtb_customer.customer_group IS NOT NULL \n";
                        $sql .= " AND dtb_customer.customer_group <> 0\n";
                        $sql .= " GROUP BY\n";
                        $sql .= " dtb_customer.customer_group;";
                        $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                        file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . 'グループ会員受注登録:' . $total . "\n", FILE_APPEND);
                        $sql = "INSERT INTO dtb_order (`group_order_id`, `customer_id`, `customer_group_id`, `order_country_id`, `order_pref`, `order_sex`, `order_job`, `payment_id`, `device_type_id`, `pre_order_id`, `message`, `order_name01`, `order_name02`, `order_kana01`, `order_kana02`, `order_company_name`, `order_email`, `order_tel01`, `order_tel02`, `order_tel03`, `order_fax01`, `order_fax02`, `order_fax03`, `order_zip01`, `order_zip02`, `order_zipcode`, `order_addr01`, `order_addr02`, `order_birth`, `subtotal`, `discount`, `delivery_fee_total`, `charge`, `tax`, `total`, `payment_total`, `payment_method`, `note`, `create_date`, `update_date`, `order_date`, `commit_date`, `payment_date`, `del_flg`, `status`)\n";
                        $sql .= " SELECT\n";
                        $sql .= " TEMP.group_order_id,\n";
                        $sql .= " TEMP.customer_id,\n";
                        $sql .= " TEMP.customer_group,\n";
                        $sql .= " TEMP.country_id,\n";
                        $sql .= " TEMP.pref,\n";
                        $sql .= " TEMP.sex,\n";
                        $sql .= " TEMP.job,\n";
                        $sql .= " 3,\n";
                        $sql .= " 99,\n";
                        $sql .= " NULL,\n";
                        $sql .= " NULL,\n";
                        $sql .= " TEMP.name01,\n";
                        $sql .= " TEMP.name02,\n";
                        $sql .= " TEMP.kana01,\n";
                        $sql .= " TEMP.kana02,\n";
                        $sql .= " TEMP.company_name,\n";
                        $sql .= " TEMP.email,\n";
                        $sql .= " TEMP.tel01,\n";
                        $sql .= " TEMP.tel02,\n";
                        $sql .= " TEMP.tel03,\n";
                        $sql .= " TEMP.fax01,\n";
                        $sql .= " TEMP.fax02,\n";
                        $sql .= " TEMP.fax03,\n";
                        $sql .= " TEMP.zip01,\n";
                        $sql .= " TEMP.zip02,\n";
                        $sql .= " TEMP.zipcode,\n";
                        $sql .= " TEMP.addr01,\n";
                        $sql .= " TEMP.addr02,\n";
                        $sql .= " TEMP.birth,\n";
                        $sql .= " TEMP.total,\n";
                        $sql .= " 0,\n";
                        $sql .= " 0,\n";
                        $sql .= " 0,\n";
                        $sql .= " 0,\n";
                        $sql .= " TEMP.total,\n";
                        $sql .= " TEMP.total,\n";
                        $sql .= ' "郵便振込",' . "\n";
                        $sql .= ' CONCAT("membership_bulk_group_", ' . $BillingId . ', "_", TEMP.customer_group, "_", TEMP.customer_id), ' . "\n";
                        $sql .= " NOW(),\n";
                        $sql .= " NOW(),\n";
                        $sql .= " NOW(),\n";
                        $sql .= " NOW(),\n";
                        $sql .= " NOW(),\n";
                        $sql .= " 0,\n";
                        $sql .= " 5\n";
                        $sql .= " FROM (\n";
                        $sql .= " SELECT \n";
                        $sql .= " INNER_TEMP.group_order_id,\n";
                        $sql .= " INNER_TEMP.customer_id,\n";
                        $sql .= " INNER_TEMP.customer_group,\n";
                        $sql .= " INNER_TEMP.country_id,\n";
                        $sql .= " INNER_TEMP.pref,\n";
                        $sql .= " INNER_TEMP.sex,\n";
                        $sql .= " INNER_TEMP.job,\n";
                        $sql .= " INNER_TEMP.name01, \n";
                        $sql .= " INNER_TEMP.name02, \n";
                        $sql .= " INNER_TEMP.kana01, \n";
                        $sql .= " INNER_TEMP.kana02, \n";
                        $sql .= " INNER_TEMP.company_name, \n";
                        $sql .= " INNER_TEMP.email, \n";
                        $sql .= " INNER_TEMP.tel01, \n";
                        $sql .= " INNER_TEMP.tel02, \n";
                        $sql .= " INNER_TEMP.tel03, \n";
                        $sql .= " INNER_TEMP.fax01, \n";
                        $sql .= " INNER_TEMP.fax02, \n";
                        $sql .= " INNER_TEMP.fax03, \n";
                        $sql .= " INNER_TEMP.zip01, \n";
                        $sql .= " INNER_TEMP.zip02, \n";
                        $sql .= " INNER_TEMP.zipcode, \n";
                        $sql .= " INNER_TEMP.addr01, \n";
                        $sql .= " INNER_TEMP.addr02, \n";
                        $sql .= " INNER_TEMP.birth,\n";
                        $sql .= " count(INNER_TEMP.product_id) AS quantity,\n";
                        $sql .= " SUM(INNER_TEMP.price) AS total\n";
                        $sql .= " FROM (\n";
                        $sql .= " SELECT\n";
                        $sql .= " dtb_membership_billing.membership_billing_id AS membership_billing_id,\n";
                        $sql .= " dtb_membership_billing_detail.membership_billing_detail_id AS membership_billing_detail_id,\n";
                        $sql .= " dtb_group_order.group_order_id AS group_order_id,\n";
                        $sql .= " dtb_customer.customer_id AS customer_id,\n";
                        $sql .= " dtb_customer.customer_group AS customer_group,\n";
                        $sql .= " dtb_customer.country_id AS country_id,\n";
                        $sql .= " dtb_customer.pref AS pref,\n";
                        $sql .= " dtb_customer.sex AS sex,\n";
                        $sql .= " dtb_customer.job AS job,\n";
                        $sql .= " dtb_customer.name01 AS name01,\n";
                        $sql .= " dtb_customer.name02 AS name02,\n";
                        $sql .= " dtb_customer.kana01 AS kana01,\n";
                        $sql .= " dtb_customer.kana02 AS kana02,\n";
                        $sql .= " dtb_customer.company_name AS company_name,\n";
                        $sql .= " dtb_customer.email AS email,\n";
                        $sql .= " dtb_customer.tel01 AS tel01,\n";
                        $sql .= " dtb_customer.tel02 AS tel02,\n";
                        $sql .= " dtb_customer.tel03 AS tel03,\n";
                        $sql .= " dtb_customer.fax01 AS fax01,\n";
                        $sql .= " dtb_customer.fax02 AS fax02,\n";
                        $sql .= " dtb_customer.fax03 AS fax03,\n";
                        $sql .= " dtb_customer.zip01 AS zip01,\n";
                        $sql .= " dtb_customer.zip02 AS zip02,\n";
                        $sql .= " dtb_customer.zipcode AS zipcode,\n";
                        $sql .= " dtb_customer.addr01 AS addr01,\n";
                        $sql .= " dtb_customer.addr02 AS addr02,\n";
                        $sql .= " dtb_customer.birth AS birth,\n";
                        $sql .= " dtb_product_class.product_id AS product_id,\n";
                        $sql .= " dtb_product_class.price02 AS price\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_membership_billing\n";
                        $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                        $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                        $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                        $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                        $sql .= ' INNER JOIN dtb_group_order ON dtb_group_order.note = CONCAT("membership_bulk_group_", ' . $BillingId . ', "_", dtb_customer.customer_group)' . "\n";
                        $sql .= " WHERE\n";
                        $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (' . "\n";
                        $sql .= " SELECT\n";
                        $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))' . "\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_order\n";
                        $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                        $sql .= " WHERE\n";
                        $sql .= " dtb_order.del_flg = 0\n";
                        $sql .= " )\n";
                        $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId . "\n";
                        $sql .= " AND dtb_customer.customer_group IS NOT NULL \n";
                        $sql .= " AND dtb_customer.customer_group <> 0\n";
                        $sql .= " GROUP BY\n";
                        $sql .= " dtb_membership_billing.membership_billing_id,\n";
                        $sql .= " dtb_membership_billing_detail.membership_billing_detail_id,\n";
                        $sql .= " dtb_customer.customer_id,\n";
                        $sql .= " dtb_product_class.product_id\n";
                        $sql .= " ) AS INNER_TEMP\n";
                        $sql .= " GROUP BY INNER_TEMP.customer_id\n";
                        $sql .= " ORDER BY INNER_TEMP.customer_id\n";
                        $sql .= " ) AS TEMP;";
                        $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                        $sql = " SELECT\n";
                        $sql .= " count(*)\n";
                        $sql .= " FROM (\n";
                        $sql .= " SELECT\n";
                        $sql .= " dtb_membership_billing.membership_billing_id,\n";
                        $sql .= " dtb_membership_billing_detail.membership_billing_detail_id,\n";
                        $sql .= " dtb_customer.customer_id,\n";
                        $sql .= " dtb_product_class.product_id\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_membership_billing\n";
                        $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                        $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                        $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                        $sql .= " INNER JOIN dtb_product ON dtb_product.product_id = dtb_product_membership.product_id\n";
                        $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                        $sql .= " WHERE\n";
                        $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (' . "\n";
                        $sql .= " SELECT\n";
                        $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))' . "\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_order\n";
                        $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                        $sql .= " WHERE\n";
                        $sql .= " dtb_order.del_flg = 0\n";
                        $sql .= " )\n";
                        $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId . "\n";
                        $sql .= " AND dtb_customer.customer_group IS NOT NULL \n";
                        $sql .= " AND dtb_customer.customer_group <> 0\n";
                        $sql .= " GROUP BY\n";
                        $sql .= " dtb_membership_billing.membership_billing_id,\n";
                        $sql .= " dtb_membership_billing_detail.membership_billing_detail_id,\n";
                        $sql .= " dtb_customer.customer_id,\n";
                        $sql .= " dtb_product_class.product_id ) AS TEMP;";
                        $totalDetail = $this->app['orm.em']->getConnection()->fetchColumn($sql);

                        file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . 'グループ会員受注詳細登録:' . $totalDetail . "\n", FILE_APPEND);
                        $sql = "INSERT INTO `dtb_order_detail` (`order_id`, `product_id`, `product_class_id`, `product_name`, `product_code`, `class_name1`, `class_name2`, `class_category_name1`, `class_category_name2`, `price`, `quantity`, `tax_rate`, `tax_rule`, `kifu_no_pub`)\n";
                        $sql .= " SELECT\n";
                        $sql .= " dtb_order.order_id AS order_id,\n";
                        $sql .= " dtb_product.product_id AS product_id,\n";
                        $sql .= " dtb_product_class.product_class_id AS product_class_id,\n";
                        $sql .= " dtb_product.name AS product_name,\n";
                        $sql .= " dtb_product_class.product_code AS product_code,\n";
                        $sql .= " NULL,\n";
                        $sql .= " NULL,\n";
                        $sql .= " NULL,\n";
                        $sql .= " NULL,\n";
                        $sql .= " dtb_product_class.price02 AS price,\n";
                        $sql .= " 1,\n";
                        $sql .= " 0,\n";
                        $sql .= " 0,\n";
                        $sql .= " 0\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_membership_billing\n";
                        $sql .= " INNER JOIN dtb_membership_billing_detail ON dtb_membership_billing_detail.membership_billing = dtb_membership_billing.membership_billing_id\n";
                        $sql .= " INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer\n";
                        $sql .= " INNER JOIN dtb_membership_billing_target_year ON dtb_membership_billing_target_year.membership_billing = dtb_membership_billing_detail.membership_billing\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_membership_id = dtb_membership_billing_target_year.product_membership\n";
                        $sql .= " INNER JOIN dtb_product ON dtb_product.product_id = dtb_product_membership.product_id\n";
                        $sql .= " INNER JOIN dtb_product_class ON dtb_product_class.product_id = dtb_product_membership.product_id\n";
                        $sql .= ' INNER JOIN dtb_order ON dtb_order.note = CONCAT("membership_bulk_group_", ' . $BillingId . ', "_", dtb_customer.customer_group, "_", dtb_customer.customer_id)' . "\n";
                        $sql .= " WHERE\n";
                        $sql .= ' CONCAT(LPAD(dtb_customer.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0")) NOT IN (' . "\n";
                        $sql .= " SELECT\n";
                        $sql .= ' CONCAT(LPAD(dtb_order.customer_id, 11, "0"),  LPAD(dtb_product_membership.product_id, 11, "0"))' . "\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_order\n";
                        $sql .= " LEFT JOIN dtb_order_detail ON dtb_order_detail.order_id = dtb_order.order_id\n";
                        $sql .= " INNER JOIN dtb_product_membership ON dtb_product_membership.product_id = dtb_order_detail.product_id\n";
                        $sql .= " WHERE\n";
                        $sql .= " dtb_order.del_flg = 0\n";
                        $sql .= " )\n";
                        $sql .= " AND dtb_membership_billing.membership_billing_id = " . $BillingId . "\n";
                        $sql .= " AND dtb_customer.customer_group IS NOT NULL \n";
                        $sql .= " AND dtb_customer.customer_group <> 0\n";
                        $sql .= " GROUP BY\n";
                        $sql .= " dtb_membership_billing.membership_billing_id,\n";
                        $sql .= " dtb_membership_billing_detail.membership_billing_detail_id,\n";
                        $sql .= " dtb_customer.customer_id,\n";
                        $sql .= " dtb_product_class.product_id;";
                        $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                        file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '一括登録情報へグループ会員受注情報登録:' . $total . "\n", FILE_APPEND);
                        $sql = 'UPDATE dtb_membership_billing_detail INNER JOIN dtb_customer ON dtb_customer.customer_id = dtb_membership_billing_detail.customer AND dtb_customer.customer_group IS NOT NULL AND dtb_customer.customer_group <> 0 INNER JOIN dtb_order ON dtb_order.note = CONCAT("membership_bulk_group_", dtb_membership_billing_detail.membership_billing, "_", dtb_customer.customer_group, "_", dtb_membership_billing_detail.customer) SET dtb_membership_billing_detail.order_id = dtb_order.order_id WHERE dtb_membership_billing_detail.membership_billing = ' . $BillingId . ';';
                        $result = $this->app['orm.em']->getConnection()->executeQuery($sql);

                        file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . 'グループ会員受注処理完了:' . $total . "\n", FILE_APPEND);
                        $sql = "UPDATE dtb_membership_billing_detail SET dtb_membership_billing_detail.status = 3, dtb_membership_billing_detail.update_date = NOW() WHERE dtb_membership_billing_detail.membership_billing = " . $BillingId . " AND dtb_membership_billing_detail.customer IN (\n";
                        $sql .= " SELECT\n";
                        $sql .= " dtb_order.customer_id\n";
                        $sql .= " FROM\n";
                        $sql .= " dtb_order\n";
                        $sql .= " WHERE\n";
                        $sql .= ' dtb_order.note LIKE CONCAT("membership_bulk_group_", ' . $BillingId . ', "%")' . "\n";
                        $sql .= " );";
                        $result = $this->app['orm.em']->getConnection()->executeQuery($sql);
                    }

                    $sql = "SELECT COUNT(*) FROM dtb_membership_billing_detail WHERE dtb_membership_billing_detail.membership_billing = " . $BillingId . " AND dtb_membership_billing_detail.status <> 3;";
                    $result = $this->app['orm.em']->getConnection()->fetchColumn($sql);
                    if (0 < $result) {
                        file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '非完了年会費受注予定異常終了更新:' . $result . "\n", FILE_APPEND);
                        $sql = "UPDATE dtb_membership_billing_detail SET dtb_membership_billing_detail.status = 4, dtb_membership_billing_detail.update_date = NOW() WHERE dtb_membership_billing_detail.membership_billing = " . $BillingId . " AND dtb_membership_billing_detail.status <> 3;";
                        $result = $this->app['orm.em']->getConnection()->executeQuery($sql);
                    }

                    $this->app['orm.em']->getConnection()->commit();
                } catch (\Exception $e) {
                    echo "予期せぬエラー:" . $e->getMessage() . "\n";
                    $this->app['orm.em']->getConnection()->rollBack();
                } finally {
                    // 処理状態更新
                    $membershipBilling->setStatus($this->app['eccube.repository.master.membership_billing_status']->find(3));
                    $this->app['orm.em']->persist($membershipBilling);
                    $this->app['orm.em']->flush();
                }
                file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . "受注処理登録完了\n", FILE_APPEND);
            }
        }
        file_put_contents($logfile_path, date('Y-m-d H:i:s: ') . '年会費受注登録バッチ終了 BillingId:' . $BillingId . "\n", FILE_APPEND);
    }
}
